# Generated by Django 5.0.4 on 2024-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewing', 'Interviewing'), ('offer_made', 'Offer Made'), ('rejected', 'Rejected'), ('hired', 'Hired')], max_length=255),
        ),
    ]
