# Generated by Django 5.0.4 on 2024-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='proficiency_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')]),
        ),
    ]
