# Generated by Django 5.0.4 on 2024-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_userskill_proficiency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='importance_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Critical')]),
        ),
    ]
