# Generated by Django 5.0.4 on 2024-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobskill_importance_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('reminder', 'Reminder'), ('announcement', 'Announcement'), ('update', 'Update')], max_length=255),
        ),
    ]
